name: Go
on: 
  pull_request:
    branches:
      - master
  push: # for test!!!
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-18.04]
    services:
        mongo:
          image: mongo:4.1
          env:
            MONGO_INITDB_ROOT_USERNAME: tester
            MONGO_INITDB_ROOT_PASSWORD: dfjgre
  
    name: Tests and deploy
    steps:
      - name: Test
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: DiscoreMe/test/testh
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.pkg.github.com
