name: Go
on: 
  pull_request:
    branches:
      - master
  push: # for test!!!
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-18.04]
    services:
        mongo:
          image: mongo:4.1
          env:
            MONGO_INITDB_ROOT_USERNAME: tester
            MONGO_INITDB_ROOT_PASSWORD: dfjgre
  
    name: Tests and deploy
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master
      
    - name: Go tests
      run: go test -v
    
    
    
