name: Go
on: 
  pull_request:
    branches:
      - master
  push: # for test!!!
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-18.04]
    
    name: Tests and deploy
    steps:
      - name: Get
        run: |
          ls
          ls /github
      - name: Test
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: discoreme/test/test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.pkg.github.com
          Dockerfile: https://github.com/DiscoreMe/test.git#master:ubuntu:18.04

