name: Go
on: 
  pull_request:
    branches:
      - master
  push: # for test!!!
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKERHUB_HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
          context: "./web"
          file: "Dockerfile"

  # build:
  #   runs-on: [ubuntu-18.04]
    
  #   name: Tests and deploy
  #   steps:
  #     - name: Test
  #       uses: elgohr/Publish-Docker-Github-Action@master
  #       with:
  #         name: discoreme/test/test
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #         registry: docker.pkg.github.com
